# Generated by Django 5.0.1 on 2024-01-19 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_delete",
            new_name="is_deleted",
        ),
    ]
