version: "3.9"

services:
  backend:
    container_name: django_app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

    volumes:
      - ./src:/src
    env_file:
      - ./.env
    depends_on:
      - redis
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    depends_on:
      - backend
  celery-beat:
    container_name: celery_beat
    command: celery -A config beat -l info
    restart: always
    build:
      context: .
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    depends_on:
      - backend
