version: "3.9"

services:
  backend:

    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn config.wsgi:application -b 0.0.0.0:8000"

    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./data/web:/vol/web
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - rabbitmq
  nginx:
    build:
      context: './nginx'
      dockerfile: './Dockerfile'
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
  db:
    container_name: database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env.dev


  redis:
    container_name: redis
    image: redis:alpine
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
  celery:
    container_name: celery
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: celery -A config worker -l INFO -Q tasks
    volumes:
      - ./src:/src
    env_file:
      - ./.env.dev
    depends_on:
      - backend
      - rabbitmq
  celery-beat:
    container_name: celery_beat
    command: celery -A config beat -l info
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - ./src:/src
    env_file:
      - ./.env.dev
    depends_on:
      - backend
volumes:
  pgdata:












