# Generated by Django 5.0.1 on 2024-01-21 17:36

import config.apps.media.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    imagekit.models.fields.ProcessedImageField(
                        height_field="height",
                        upload_to=config.apps.media.models.upload_to,
                        width_field="width",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                ("resize_width", models.PositiveIntegerField(default=0)),
                ("resize_height", models.PositiveIntegerField(default=0)),
                ("width", models.IntegerField(editable=False)),
                ("height", models.IntegerField(editable=False)),
                (
                    "file_hash",
                    models.CharField(db_index=True, editable=False, max_length=40),
                ),
                ("file_size", models.PositiveIntegerField(editable=False, null=True)),
                ("focal_point_x", models.PositiveIntegerField(blank=True, null=True)),
                ("focal_point_y", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "focal_point_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "focal_point_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "medias",
                "ordering": ("-created_at", "-modified_at"),
            },
        ),
    ]
