# Generated by Django 5.0.1 on 2024-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_userpasswordresettoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreviousdetailhistory",
            name="field",
            field=models.CharField(
                choices=[
                    ("نام کاربری", "Username"),
                    ("شماره موبایل", "Phone"),
                    ("ایمیل", "Email"),
                ],
                max_length=12,
            ),
        ),
    ]
