# Generated by Django 5.0.1 on 2024-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userfavoriteproduct_userrecentvisitedproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersearchhistory",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="usersearchhistory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="usersearchhistory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersearchhistory",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
