# Generated by Django 5.0.1 on 2024-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_rename_date_created_usersearchhistory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreviousdetailhistory",
            name="new_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userpreviousdetailhistory",
            name="old_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
