# Generated by Django 5.0.1 on 2024-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userpreviousdetailhistory_new_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="before_delete_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="before_delete_phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="before_delete_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
