# Generated by Django 5.0.1 on 2024-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_uservisits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=25, verbose_name="last name"),
        ),
    ]
