# Generated by Django 5.0.1 on 2024-01-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_optiongroup_alter_brand_order_alter_category_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("buy_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("sale_price", models.PositiveBigIntegerField()),
                ("num_stock", models.PositiveIntegerField(default=0)),
                (
                    "threshold_low_stack",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockrecords",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
