# Generated by Django 5.0.1 on 2024-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="special_sale_price",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="special_sale_price_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="special_sale_price_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
