# Generated by Django 5.0.1 on 2024-01-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_stockrecord_special_sale_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="as_placeholder",
            field=models.BooleanField(default=False),
        ),
    ]
