# Generated by Django 5.0.1 on 2024-01-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_remove_product_tn_ancestors_count_and_more"),
        ("inventory", "0003_stockrecord_as_placeholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stockrecords",
                to="catalog.product",
            ),
        ),
    ]
