# Generated by Django 5.0.1 on 2024-01-30 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_stockrecord_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockrecord",
            name="as_placeholder",
        ),
    ]
