# Generated by Django 5.0.1 on 2024-02-07 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_stockrecord_as_placeholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockrecord",
            name="sku",
        ),
    ]
