# Generated by Django 5.0.1 on 2024-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_remove_stockrecord_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="sku",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
