# Generated by Django 5.0.1 on 2024-01-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerifyOTPService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PHONE", "تلفن"), ("EMAIL", "ایمیل")], max_length=5
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATE", "احراز هویت"),
                            ("RESET_PASSWORD", "بازیابی کلمه عبور"),
                            ("VERIFY", "تایید"),
                        ],
                        default="AUTHENTICATE",
                        max_length=14,
                    ),
                ),
                ("to", models.CharField(max_length=355)),
                ("code", models.CharField(max_length=5)),
                ("expire_at", models.DateTimeField()),
            ],
            options={
                "db_table": "verify_otp_messages",
            },
        ),
    ]
