# Generated by Django 5.0.1 on 2024-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifyotpservice",
            name="type",
            field=models.CharField(
                choices=[("شماره موبایل", "Phone"), ("ایمیل", "Email")], max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="verifyotpservice",
            name="usage",
            field=models.CharField(
                choices=[
                    ("احراز هویت", "Authenticate"),
                    ("بازیابی کلمه عبور", "Reset Password"),
                    ("تایید", "Verify"),
                ],
                default="احراز هویت",
                max_length=17,
            ),
        ),
    ]
