# Generated by Django 5.0.1 on 2024-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0003_alter_verifyotpservice_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifyotpservice",
            name="type",
            field=models.CharField(
                choices=[("شماره موبایل", "Phone"), ("ایمیل", "Email")], max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="verifyotpservice",
            name="usage",
            field=models.CharField(
                choices=[
                    ("احراز هویت", "Authenticate"),
                    ("بازیابی کلمه عبور", "Reset Password"),
                    ("تایید", "Verify"),
                ],
                default="احراز هویت",
                max_length=17,
            ),
        ),
    ]
