# Generated by Django 5.0.1 on 2024-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0004_alter_verifyotpservice_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifyotpservice",
            name="type",
            field=models.CharField(
                choices=[("Phone", "Phone"), ("Email", "Email")], max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="verifyotpservice",
            name="usage",
            field=models.CharField(
                choices=[
                    ("Authentication", "Authenticate"),
                    ("Password Reset", "Reset Password"),
                    ("Verification", "Verify"),
                ],
                default="Authentication",
                max_length=17,
            ),
        ),
    ]
