# Generated by Django 5.0.1 on 2024-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0005_alter_verifyotpservice_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifyotpservice",
            name="type",
            field=models.CharField(
                choices=[("PHONE", "Phone"), ("EMAIL", "Email")], max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="verifyotpservice",
            name="usage",
            field=models.CharField(
                choices=[
                    ("AUTHENTICATE", "Authenticate"),
                    ("RESET_PASSWORD", "Reset Password"),
                    ("VERIFY", "Verify"),
                ],
                default="AUTHENTICATE",
                max_length=17,
            ),
        ),
    ]
