# Generated by Django 5.0.1 on 2024-02-16 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0007_remove_coupon_only_brands_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("پرداخت موفق", "Success"),
                            ("پرداخت ناموفق", "Failed"),
                            ("نا مشخص", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("failed_reason", models.TextField(blank=True, null=True)),
                (
                    "transaction_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("ref_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="order.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ("-created_at",),
            },
        ),
    ]
