# Generated by Django 5.0.1 on 2024-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("پرداخت موفق", "Success"),
                    ("پرداخت ناموفق", "Failed"),
                    ("نا مشخص", "Other"),
                    ("پرداخت توسط کاربر کنسل شده است", "Cancel By User"),
                    ("در انتظار برای انتقال کاربر به درگاه بانک", "Waiting"),
                    ("کاربر از درگاه برگشته", "Return From Bank"),
                ],
                max_length=55,
                null=True,
            ),
        ),
    ]
