# Generated by Django 5.0.1 on 2024-01-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_optiongroup_alter_brand_order_alter_category_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiongroupvalue",
            name="color_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
