# Generated by Django 5.0.1 on 2024-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_productproperty_productpropertyvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, null=True, unique=True
            ),
        ),
    ]
