# Generated by Django 5.0.1 on 2024-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_remove_product_tn_ancestors_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
