# Generated by Django 5.0.1 on 2024-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
