# Generated by Django 5.0.1 on 2024-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_public",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="structure",
            field=models.CharField(
                choices=[
                    ("standalone", "Standalone"),
                    ("parent", "Parent"),
                    ("child", "Child"),
                ],
                db_index=True,
                default="standalone",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_ir",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
