# Generated by Django 5.0.1 on 2024-02-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0015_alter_optiongroupvalue_group_alter_product_is_public_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="optiongroup",
            name="filter_param_name",
            field=models.CharField(default="s", max_length=20),
            preserve_default=False,
        ),
    ]
