# Generated by Django 5.0.1 on 2024-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_optiongroup_filter_param_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiongroup",
            name="filter_contain",
            field=models.BooleanField(default=False),
        ),
    ]
