# Generated by Django 5.0.1 on 2024-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_optiongroup_filter_contain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optiongroup",
            name="filter_param_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
