# Generated by Django 5.0.1 on 2024-02-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_optiongroup_filter_param_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optiongroupvalue",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_group_values",
                to="catalog.optiongroup",
            ),
        ),
    ]
