# Generated by Django 5.0.1 on 2024-02-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_alter_optiongroupvalue_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproperty",
            name="product_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="catalog.productclass",
            ),
        ),
    ]
