# Generated by Django 5.0.1 on 2024-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_productproperty_product_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productproperty",
            name="product_class",
        ),
        migrations.AddField(
            model_name="productclass",
            name="properties",
            field=models.ManyToManyField(to="catalog.productproperty"),
        ),
    ]
