# Generated by Django 5.0.1 on 2024-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.AddField(
            model_name="product",
            name="short_slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, editable=False, null=True, unique=True
            ),
        ),
    ]
