# Generated by Django 5.0.1 on 2024-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0024_alter_productattributevalue_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_slug",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
    ]
