# Generated by Django 5.0.1 on 2024-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_productcomment_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productclass",
            name="properties",
            field=models.ManyToManyField(
                blank=True, null=True, to="catalog.productproperty"
            ),
        ),
    ]
