# Generated by Django 5.0.1 on 2024-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_alter_productclass_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productclass",
            name="properties",
            field=models.ManyToManyField(blank=True, to="catalog.productproperty"),
        ),
    ]
