# Generated by Django 5.0.1 on 2024-01-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_banner_expire_at_banner_start_at"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ("-order",),
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="banners",
                to="media.media",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
