# Generated by Django 5.0.1 on 2024-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_banner_options_alter_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
