# Generated by Django 5.0.1 on 2024-02-15 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_shippingrate_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="only_brands",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="only_categories",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="only_products",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="only_users",
        ),
    ]
