# Generated by Django 5.0.1 on 2024-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_remove_coupon_only_brands_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="lock_modify_until",
        ),
        migrations.AddField(
            model_name="order",
            name="lock",
            field=models.BooleanField(default=False),
        ),
    ]
