# Generated by Django 5.0.1 on 2024-02-16 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_remove_order_lock_modify_until_order_lock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderaddress",
            old_name="receiver_fullname",
            new_name="receiver_family",
        ),
        migrations.AddField(
            model_name="orderaddress",
            name="receiver_building_number",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="orderaddress",
            name="receiver_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderaddress",
            name="receiver_unit",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
