# Generated by Django 5.0.1 on 2024-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_orderitem_final_buy_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="verified_payment",
            field=models.BooleanField(default=False),
        ),
    ]
